/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao.servServico;

import javax.swing.JOptionPane;
import service.ServicoService;

/**
 *
 * @author Samuel
 */
public class InsertServico extends javax.swing.JDialog {

    private ServicoService servServ;

    /**
     * Creates new form InsertServico
     */
    public InsertServico(java.awt.Frame parent, boolean modal, ServicoService service) {
        super(parent, modal);
        initComponents();
        servServ = service;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodServ = new javax.swing.JTextField();
        txtNomeServ = new javax.swing.JTextField();
        txtValorServ = new javax.swing.JTextField();
        InserirServiço = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4), javax.swing.BorderFactory.createTitledBorder("")));

        buttonConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        buttonConfirmar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConfirmar);

        buttonFechar.setBackground(new java.awt.Color(0, 0, 0));
        buttonFechar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonFechar.setForeground(new java.awt.Color(255, 255, 255));
        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFechar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Valor:");

        txtCodServ.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodServ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodServActionPerformed(evt);
            }
        });

        txtNomeServ.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtNomeServ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNomeServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeServActionPerformed(evt);
            }
        });

        txtValorServ.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtValorServ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtValorServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorServActionPerformed(evt);
            }
        });

        InserirServiço.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir Serviço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Malgun Gothic", 1, 24)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1))); // NOI18N

        javax.swing.GroupLayout InserirServiçoLayout = new javax.swing.GroupLayout(InserirServiço);
        InserirServiço.setLayout(InserirServiçoLayout);
        InserirServiçoLayout.setHorizontalGroup(
            InserirServiçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        InserirServiçoLayout.setVerticalGroup(
            InserirServiçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtValorServ, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtNomeServ)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(txtCodServ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(InserirServiço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(InserirServiço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodServ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorServ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(416, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:

        model.Servico aux = new model.Servico();

        try {
            aux.setCodigo(Integer.parseInt(txtCodServ.getText()));
            aux.setNome(txtNomeServ.getText());
            aux.setValor(Float.parseFloat(txtValorServ.getText()));
            if (servServ.inserir(aux) == true) {
                JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso. :)");
            } else {
                JOptionPane.showMessageDialog(this, "Falha no cadastro do serviço. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha no cadastro do serviço valor ou código inserido inválido. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();//mata a janela
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void txtCodServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodServActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodServActionPerformed

    private void txtNomeServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeServActionPerformed

    private void txtValorServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorServActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InserirServiço;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCodServ;
    private javax.swing.JTextField txtNomeServ;
    private javax.swing.JTextField txtValorServ;
    // End of variables declaration//GEN-END:variables
}
