/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import javax.swing.JOptionPane;
import service.AnimalService;
import service.AtendimentoService;
import service.ServicoService;

/**
 *
 * @author Samuel
 */
public class Atendimento extends javax.swing.JDialog {

    private AtendimentoService atenServ;

    /**
     * Creates new form Atendimento
     */
    public Atendimento(java.awt.Frame parent, boolean modal, AtendimentoService service) {
        super(parent, modal);
        initComponents();
        atenServ = service;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodServAtend = new javax.swing.JTextField();
        txtCodAtend = new javax.swing.JTextField();
        txtDtaAtend = new javax.swing.JTextField();
        txtCodAnimAtend = new javax.swing.JTextField();
        LancarAtend = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4), javax.swing.BorderFactory.createTitledBorder("")));

        buttonConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        buttonConfirmar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConfirmar);

        buttonFechar.setBackground(new java.awt.Color(0, 0, 0));
        buttonFechar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonFechar.setForeground(new java.awt.Color(255, 255, 255));
        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFechar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Data (dd/MM/yy):");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Código do animal:");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Código do serviço:");

        txtCodServAtend.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodServAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodServAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodServAtendActionPerformed(evt);
            }
        });

        txtCodAtend.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAtendActionPerformed(evt);
            }
        });

        txtDtaAtend.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtDtaAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDtaAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtaAtendActionPerformed(evt);
            }
        });

        txtCodAnimAtend.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodAnimAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodAnimAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAnimAtendActionPerformed(evt);
            }
        });

        LancarAtend.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lançar Atendimento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Malgun Gothic", 1, 24)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1))); // NOI18N

        javax.swing.GroupLayout LancarAtendLayout = new javax.swing.GroupLayout(LancarAtend);
        LancarAtend.setLayout(LancarAtendLayout);
        LancarAtendLayout.setHorizontalGroup(
            LancarAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LancarAtendLayout.setVerticalGroup(
            LancarAtendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodAnimAtend)
                            .addComponent(txtDtaAtend)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                    .addComponent(txtCodAtend, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodServAtend, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel4)))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addComponent(LancarAtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LancarAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDtaAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodAnimAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodServAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(416, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:

        model.Atendimento aux = new model.Atendimento();
        AnimalService aniServ = new AnimalService();
        ServicoService servServ = new ServicoService();

        try {

            aux.setCodigo(Integer.parseInt(txtCodAtend.getText()));
            aux.setDate(util.Util.stringParaDate(txtDtaAtend.getText()));
            aux.setAnimal(aniServ.getAnimal(Integer.parseInt(txtCodAnimAtend.getText())));
            aux.setServico(servServ.getServico(Integer.parseInt(txtCodServAtend.getText())));

            if (atenServ.inserir(aux) == true) {
                JOptionPane.showMessageDialog(this, "Atendimento lançado com sucesso. :)");
            } else {
                JOptionPane.showMessageDialog(this, "Falha no lançamento do atendimento. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha no lançamento do atendimento, algum código inserido é inválido. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();//mata a janela
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void txtCodServAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodServAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodServAtendActionPerformed

    private void txtCodAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAtendActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodAtendActionPerformed

    private void txtDtaAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtaAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtaAtendActionPerformed

    private void txtCodAnimAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAnimAtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodAnimAtendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LancarAtend;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCodAnimAtend;
    private javax.swing.JTextField txtCodAtend;
    private javax.swing.JTextField txtCodServAtend;
    private javax.swing.JTextField txtDtaAtend;
    // End of variables declaration//GEN-END:variables
}
