/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import javax.swing.JOptionPane;
import service.AnimalService;
import service.AtendimentoService;
import service.ServicoService;
import util.Util;

/**
 *
 * @author Alunos
 */
public class Home extends javax.swing.JDialog {

    /**
     * Creates new form Home
     *
     */
    public Home(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastroAnimal = new javax.swing.JButton();
        ListaAnimal = new javax.swing.JButton();
        CadastroServico = new javax.swing.JButton();
        LancaAtend = new javax.swing.JButton();
        ListaServico = new javax.swing.JButton();
        ListaAtendimentos = new javax.swing.JButton();
        LimparBD = new javax.swing.JButton();
        EmitirNF = new javax.swing.JButton();
        RelatMaiorValorAtend = new javax.swing.JButton();
        RelatMenorValorAtend = new javax.swing.JButton();
        RelatTotalValorAtend = new javax.swing.JButton();
        RelatAtendPeriod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de opções", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Malgun Gothic", 1, 18)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1))); // NOI18N
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        CadastroAnimal.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        CadastroAnimal.setText("Cadastro de animal");
        CadastroAnimal.setToolTipText("");
        CadastroAnimal.setAlignmentY(0.0F);
        CadastroAnimal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CadastroAnimal.setFocusable(false);
        CadastroAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadastroAnimal.setPreferredSize(new java.awt.Dimension(99, 23));
        CadastroAnimal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CadastroAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAnimalActionPerformed(evt);
            }
        });

        ListaAnimal.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        ListaAnimal.setText("Listar Animais");
        ListaAnimal.setToolTipText("");
        ListaAnimal.setAlignmentY(0.0F);
        ListaAnimal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaAnimal.setFocusable(false);
        ListaAnimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaAnimal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ListaAnimal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ListaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAnimalActionPerformed(evt);
            }
        });

        CadastroServico.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        CadastroServico.setText("Cadastro de serviço");
        CadastroServico.setToolTipText("");
        CadastroServico.setAlignmentY(0.0F);
        CadastroServico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CadastroServico.setFocusable(false);
        CadastroServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadastroServico.setPreferredSize(new java.awt.Dimension(99, 23));
        CadastroServico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CadastroServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CadastroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroServicoActionPerformed(evt);
            }
        });

        LancaAtend.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        LancaAtend.setText("Lançamento de atendimento");
        LancaAtend.setToolTipText("");
        LancaAtend.setAlignmentY(0.0F);
        LancaAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LancaAtend.setFocusable(false);
        LancaAtend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LancaAtend.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LancaAtend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LancaAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancaAtendActionPerformed(evt);
            }
        });

        ListaServico.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        ListaServico.setText("Listar Serviços");
        ListaServico.setToolTipText("");
        ListaServico.setAlignmentY(0.0F);
        ListaServico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaServico.setFocusable(false);
        ListaServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaServico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ListaServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ListaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaServicoActionPerformed(evt);
            }
        });

        ListaAtendimentos.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        ListaAtendimentos.setText("Listar Atendimentos");
        ListaAtendimentos.setToolTipText("");
        ListaAtendimentos.setAlignmentY(0.0F);
        ListaAtendimentos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListaAtendimentos.setFocusable(false);
        ListaAtendimentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaAtendimentos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ListaAtendimentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ListaAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaAtendimentosActionPerformed(evt);
            }
        });

        LimparBD.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        LimparBD.setText("Limpar Banco de Dados");
        LimparBD.setToolTipText("");
        LimparBD.setAlignmentY(0.0F);
        LimparBD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LimparBD.setFocusable(false);
        LimparBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LimparBD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LimparBD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LimparBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparBDActionPerformed(evt);
            }
        });

        EmitirNF.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        EmitirNF.setText("Emitir Nota Fiscal");
        EmitirNF.setToolTipText("");
        EmitirNF.setAlignmentY(0.0F);
        EmitirNF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EmitirNF.setFocusable(false);
        EmitirNF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EmitirNF.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EmitirNF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EmitirNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmitirNFActionPerformed(evt);
            }
        });

        RelatMaiorValorAtend.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        RelatMaiorValorAtend.setText("<html>Relatório<br>\nMaior valor de atendimento do animal");
        RelatMaiorValorAtend.setToolTipText("");
        RelatMaiorValorAtend.setAlignmentY(0.0F);
        RelatMaiorValorAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RelatMaiorValorAtend.setFocusable(false);
        RelatMaiorValorAtend.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RelatMaiorValorAtend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatMaiorValorAtend.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RelatMaiorValorAtend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RelatMaiorValorAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatMaiorValorAtendActionPerformed(evt);
            }
        });

        RelatMenorValorAtend.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        RelatMenorValorAtend.setText("<html>Relatório<br>\nMenor valor de atendimento do animal");
        RelatMenorValorAtend.setToolTipText("");
        RelatMenorValorAtend.setAlignmentY(0.0F);
        RelatMenorValorAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RelatMenorValorAtend.setFocusable(false);
        RelatMenorValorAtend.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RelatMenorValorAtend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatMenorValorAtend.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RelatMenorValorAtend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RelatMenorValorAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatMenorValorAtendActionPerformed(evt);
            }
        });

        RelatTotalValorAtend.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        RelatTotalValorAtend.setText("<html>Relatório<br>\nTotalizar os atendimentos do animal");
        RelatTotalValorAtend.setToolTipText("");
        RelatTotalValorAtend.setAlignmentY(0.0F);
        RelatTotalValorAtend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RelatTotalValorAtend.setFocusable(false);
        RelatTotalValorAtend.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RelatTotalValorAtend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatTotalValorAtend.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RelatTotalValorAtend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RelatTotalValorAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatTotalValorAtendActionPerformed(evt);
            }
        });

        RelatAtendPeriod.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        RelatAtendPeriod.setText("<html>Relatório<br>\nAtendimentos entre um período");
        RelatAtendPeriod.setToolTipText("");
        RelatAtendPeriod.setAlignmentY(0.0F);
        RelatAtendPeriod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RelatAtendPeriod.setFocusable(false);
        RelatAtendPeriod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RelatAtendPeriod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatAtendPeriod.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RelatAtendPeriod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RelatAtendPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatAtendPeriodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(CadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastroServico, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LancaAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmitirNF, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatMaiorValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimparBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatMenorValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatTotalValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RelatAtendPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastroServico, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LancaAtend, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListaAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmitirNF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LimparBD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatMaiorValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatMenorValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatTotalValorAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatAtendPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(366, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAnimalActionPerformed
        // TODO add your handling code here:
        Animal dialog = new Animal(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //fecha a telinha sem fechar todo o programa
                dialog.setVisible(false);
                dialog.dispose();//mata a janela

            }
        });
        dialog.setVisible(true);

    }//GEN-LAST:event_CadastroAnimalActionPerformed

    private void ListaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAnimalActionPerformed
        // TODO add your handling code here:

        AnimalService aniServ = new AnimalService();
        if (aniServ.toString() != null) {
            JOptionPane.showMessageDialog(this, aniServ, "Listando animais", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Não há nenhum animal cadastrado.", "Listando animais", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ListaAnimalActionPerformed

    private void CadastroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroServicoActionPerformed
        // TODO add your handling code here:
        Servico dialog = new Servico(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                
                dialog.setVisible(false);
                dialog.dispose();//mata a janela

            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_CadastroServicoActionPerformed

    private void LancaAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancaAtendActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtendimentoService atendServ = new AtendimentoService();
                Atendimento dialog = new Atendimento(new javax.swing.JFrame(), true, atendServ);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.setVisible(false);
                        dialog.dispose();//mata a janela
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_LancaAtendActionPerformed

    private void ListaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaServicoActionPerformed
        // TODO add your handling code here:
        ServicoService servServ = new ServicoService();
        if (servServ.toString() != null) {
            JOptionPane.showMessageDialog(this, servServ, "Listando serviços", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Não há nenhum serviço cadastrado.", "Listando animais", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ListaServicoActionPerformed

    private void ListaAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaAtendimentosActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();
        if (atendServ.toString() != null) {
            JOptionPane.showMessageDialog(this, atendServ, "Listando atendimentos", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Não há nenhum atendimento lançado.", "Listando animais", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_ListaAtendimentosActionPerformed

    private void LimparBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparBDActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();
        ServicoService servServ = new ServicoService();
        AnimalService aniServ = new AnimalService();

        int aux = JOptionPane.showConfirmDialog(this, "Deseja realmente limpar o banco de dados", "Limpando Banco de Dados", JOptionPane.YES_NO_OPTION);

        if (aux == JOptionPane.YES_OPTION) {
            atendServ.limpaDados();
            servServ.limpaDados();
            aniServ.limpaDados();

            JOptionPane.showMessageDialog(this, "Banco de dados excluído com sucesso.", "Confirmação de exclusão", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_LimparBDActionPerformed

    private void EmitirNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmitirNFActionPerformed
        // TODO add your handling code here:

        AtendimentoService atendServ = new AtendimentoService();

        String aux = JOptionPane.showInputDialog(this, "Insira o código do animal: ");

        try {
            JOptionPane.showMessageDialog(this, atendServ.getNotaFiscal(Integer.parseInt(aux)), "Gerando NF", JOptionPane.PLAIN_MESSAGE);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha na geração da NF, código inserido inválido. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_EmitirNFActionPerformed

    private void RelatMaiorValorAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatMaiorValorAtendActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();

        String aux = JOptionPane.showInputDialog(this, "Insira o código do animal: ");

        try {
            if (atendServ.getMaiorAtendimento(Integer.parseInt(aux)) != null) {
                JOptionPane.showMessageDialog(this, atendServ.getMaiorAtendimento(Integer.parseInt(aux)), "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Não há nenhum atendimento lançado.", "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha na geração do relatório, código inserido inválido. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_RelatMaiorValorAtendActionPerformed

    private void RelatMenorValorAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatMenorValorAtendActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();

        String aux = JOptionPane.showInputDialog(this, "Insira o código do animal: ");

        try {
            if (atendServ.getMenorAtendimento(Integer.parseInt(aux)) != null) {
                JOptionPane.showMessageDialog(this, atendServ.getMenorAtendimento(Integer.parseInt(aux)), "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Não há nenhum atendimento lançado.", "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha na geração do relatório, código inserido inválido. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RelatMenorValorAtendActionPerformed

    private void RelatTotalValorAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatTotalValorAtendActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();

        String aux = JOptionPane.showInputDialog(this, "Insira o código do animal: ");

        try {
            if (atendServ.getTotalAtendimentos(Integer.parseInt(aux)) != 0) {
                JOptionPane.showMessageDialog(this, "Total dos atendimentos = " + atendServ.getTotalAtendimentos(Integer.parseInt(aux)), "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Não há nenhum atendimento lançado.", "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Falha na geração do relatório, código inserido inválido. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RelatTotalValorAtendActionPerformed

    private void RelatAtendPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatAtendPeriodActionPerformed
        // TODO add your handling code here:
        AtendimentoService atendServ = new AtendimentoService();

        String aux = JOptionPane.showInputDialog(this, "Insira a data inicial(dd/MM/yy): ");
        String aux2 = JOptionPane.showInputDialog(this, "Insira a data final(dd/MM/yy): ");

        if ((Util.stringParaDate(aux)) != null) {
            if ((Util.stringParaDate(aux2)) != null) {
                if (atendServ.getAtendimentosPorPeriodo(aux, aux2) != "") {
                    JOptionPane.showMessageDialog(this, atendServ.getAtendimentosPorPeriodo(aux, aux2), "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Não há nenhum atendimento entre o período inserido.", "Gerando Relatório", JOptionPane.PLAIN_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Falha na geração do relatório, data final inserida inválida. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Falha na geração do relatório, data inicial inserida inválida. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_RelatAtendPeriodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroAnimal;
    private javax.swing.JButton CadastroServico;
    private javax.swing.JButton EmitirNF;
    private javax.swing.JButton LancaAtend;
    private javax.swing.JButton LimparBD;
    private javax.swing.JButton ListaAnimal;
    private javax.swing.JButton ListaAtendimentos;
    private javax.swing.JButton ListaServico;
    private javax.swing.JButton RelatAtendPeriod;
    private javax.swing.JButton RelatMaiorValorAtend;
    private javax.swing.JButton RelatMenorValorAtend;
    private javax.swing.JButton RelatTotalValorAtend;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
