/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao.servAnimal;

import javax.swing.JOptionPane;
import service.AnimalService;
import util.DocumentException;

/**
 *
 * @author Samuel
 */
public class AlteraAnimal extends javax.swing.JDialog {

    private AnimalService aniServ;

    /**
     * Creates new form AlteraAnimal
     */
    public AlteraAnimal(java.awt.Frame parent, boolean modal, AnimalService service) {
        super(parent, modal);
        initComponents();
        aniServ = service;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonConfirmar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCidadeAnim = new javax.swing.JTextField();
        txtCodAnim = new javax.swing.JTextField();
        txtNomeAnim = new javax.swing.JTextField();
        txtEnderAnim = new javax.swing.JTextField();
        InserirAnimal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodAlterAnim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tipoAnimal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4), javax.swing.BorderFactory.createTitledBorder("")));

        buttonConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        buttonConfirmar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonConfirmar);

        buttonFechar.setBackground(new java.awt.Color(0, 0, 0));
        buttonFechar.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        buttonFechar.setForeground(new java.awt.Color(255, 255, 255));
        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFechar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Novo código:");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Novo nome:");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Novo endereço:");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Nova cidade:");

        txtCidadeAnim.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCidadeAnim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCidadeAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeAnimActionPerformed(evt);
            }
        });

        txtCodAnim.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodAnim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAnimActionPerformed(evt);
            }
        });

        txtNomeAnim.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtNomeAnim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNomeAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAnimActionPerformed(evt);
            }
        });

        txtEnderAnim.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtEnderAnim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEnderAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderAnimActionPerformed(evt);
            }
        });

        InserirAnimal.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Animal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Malgun Gothic", 1, 24)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1))); // NOI18N

        javax.swing.GroupLayout InserirAnimalLayout = new javax.swing.GroupLayout(InserirAnimal);
        InserirAnimal.setLayout(InserirAnimalLayout);
        InserirAnimalLayout.setHorizontalGroup(
            InserirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        InserirAnimalLayout.setVerticalGroup(
            InserirAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Código do animal a ser alterado:");

        txtCodAlterAnim.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        txtCodAlterAnim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodAlterAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodAlterAnimActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Tipo:");

        tipoAnimal.setFont(new java.awt.Font("BankGothic Lt BT", 0, 16)); // NOI18N
        tipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato" }));
        tipoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InserirAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEnderAnim)
                                .addComponent(txtNomeAnim)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(txtCodAnim, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCidadeAnim, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodAlterAnim, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(InserirAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodAlterAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnderAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCidadeAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(416, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:
        
        String tipo = tipoAnimal.getSelectedItem().toString();
        
        if(tipo.equals("Cachorro")){
            model.Cachorro aux = new model.Cachorro();
            String perdigree = JOptionPane.showInputDialog("O cachorro vai possui perdigree?(S-Sim/N-Não)");
            perdigree = perdigree.toUpperCase();
            if(perdigree.equals("S")){
                aux.setPerdigree(true);
            }else if(perdigree.equals("N")){
                aux.setPerdigree(false);
            }else{
                JOptionPane.showMessageDialog(this, "Falha na alteração do animal perdigree inserido inválido. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try{

            int auxCod = Integer.parseInt(txtCodAlterAnim.getText());
            aux.setCodigo(Integer.parseInt(txtCodAnim.getText()));
            aux.setNome(txtNomeAnim.getText());
            aux.setEndereco(txtEnderAnim.getText());
            aux.setCidade(txtCidadeAnim.getText());

            if (aniServ.alterar(auxCod, aux) == true)
                JOptionPane.showMessageDialog(this, "Animal alterado com sucesso. :)");
            else
                JOptionPane.showMessageDialog(this, "Falha na alteração do animal. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(this, "Falha na alteração do animal código inserido inválido. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if(tipo.equals("Gato")){
               
            model.Gato aux = new model.Gato();
            
            String tipoDocumento = JOptionPane.showInputDialog("Insira o tipo de documento do dono:");
            tipoDocumento = tipoDocumento.toUpperCase();
            if(tipoDocumento.equals("CPF")){
                String dados = JOptionPane.showInputDialog("Insira o numero do documento:");
                try{
                    aux.setNumeroDocumento(dados, tipoDocumento);
                }catch(DocumentException e){
                    JOptionPane.showMessageDialog(this, e.getMessage(),  "ERRO", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }else if(tipoDocumento.equals("CNPJ")){
                String dados = JOptionPane.showInputDialog("Insira o numero do documento:");
                try{
                    aux.setNumeroDocumento(dados, tipoDocumento);
                }catch(DocumentException e){
                    JOptionPane.showMessageDialog(this, e.getMessage(),  "ERRO", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Falha na inserção do animal tipo de documento inserido inválido. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try{

            int auxCod = Integer.parseInt(txtCodAlterAnim.getText());
            aux.setCodigo(Integer.parseInt(txtCodAnim.getText()));
            aux.setNome(txtNomeAnim.getText());
            aux.setEndereco(txtEnderAnim.getText());
            aux.setCidade(txtCidadeAnim.getText());

            if (aniServ.alterar(auxCod, aux) == true)
                JOptionPane.showMessageDialog(this, "Animal alterado com sucesso. :)");
            else
                JOptionPane.showMessageDialog(this, "Falha na alteração do animal. :(", "ERRO", JOptionPane.ERROR_MESSAGE);
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(this, "Falha na alteração do animal código inserido inválido. :(",  "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();//mata a janela
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void txtCidadeAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeAnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeAnimActionPerformed

    private void txtCodAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAnimActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCodAnimActionPerformed

    private void txtNomeAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAnimActionPerformed

    private void txtEnderAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderAnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderAnimActionPerformed

    private void txtCodAlterAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodAlterAnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodAlterAnimActionPerformed

    private void tipoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InserirAnimal;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tipoAnimal;
    private javax.swing.JTextField txtCidadeAnim;
    private javax.swing.JTextField txtCodAlterAnim;
    private javax.swing.JTextField txtCodAnim;
    private javax.swing.JTextField txtEnderAnim;
    private javax.swing.JTextField txtNomeAnim;
    // End of variables declaration//GEN-END:variables
}
